" ~/dev/redirect-lab/redirectioner/.session.vim:
" Vim session script.
" Created by session.vim 2.13.1 on 07 November 2021 at 21:36:05.
" Open this file in Vim and run :source % to restore your session.

if exists('g:syntax_on') != 1 | syntax on | endif
if exists('g:did_load_filetypes') != 1 | filetype on | endif
if exists('g:did_load_ftplugin') != 1 | filetype plugin on | endif
if exists('g:did_indent_on') != 1 | filetype indent on | endif
if &background != 'dark'
	set background=dark
endif
if !exists('g:colors_name') || g:colors_name != 'one' | colorscheme one | endif
call setqflist([])
let SessionLoad = 1
if &cp | set nocp | endif
let s:so_save = &g:so | let s:siso_save = &g:siso | setg so=0 siso=0 | setl so=-1 siso=-1
let v:this_session=expand("<sfile>:p")
silent only
silent tabonly
cd ~/dev/redirect-lab/redirectioner
if expand('%') == '' && !&modified && line('$') <= 1 && getline(1) == ''
  let s:wipebuf = bufnr('%')
endif
set shortmess=aoO
argglobal
%argdel
edit app/Http/Controllers/LinksController.php
argglobal
balt app/Http/Controllers/Auth/PasswordResetLinkController.php
setlocal fdm=manual
setlocal fde=0
setlocal fmr={{{,}}}
setlocal fdi=#
setlocal fdl=0
setlocal fml=1
setlocal fdn=20
setlocal nofen
silent! normal! zE
let &fdl = &fdl
let s:l = 58 - ((8 * winheight(0) + 10) / 21)
if s:l < 1 | let s:l = 1 | endif
keepjumps exe s:l
normal! zt
keepjumps 58
normal! 017|
lcd ~/dev/redirect-lab/redirectioner
tabnext 1
badd +3 ~/dev/redirect-lab/redirectioner/package.json
badd +4 ~/dev/redirect-lab/redirectioner/resources/css/app.css
badd +1 ~/dev/redirect-lab/redirectioner/resources
badd +1 ~/dev/redirect-lab/redirectioner/tailwind.config.js
badd +14 ~/dev/redirect-lab/redirectioner/webpack.mix.js
badd +11 ~/dev/redirect-lab/redirectioner/resources/views/components/links/table.blade.php
badd +15 ~/dev/redirect-lab/redirectioner/resources/views/layouts/app.blade.php
badd +28 ~/dev/redirect-lab/redirectioner/app/Traits/HasHashColumn.php
badd +9 ~/dev/redirect-lab/redirectioner/app/Models/LinkVisits.php
badd +15 ~/dev/redirect-lab/redirectioner/app/Models/Link.php
badd +554 ~/dev/redirect-lab/redirectioner/vendor/laravel/framework/src/Illuminate/Support/Str.php
badd +12 ~/dev/redirect-lab/redirectioner/resources/views/dashboard.blade.php
badd +13 ~/dev/redirect-lab/redirectioner/resources/views/components/links/form.blade.php
badd +26 ~/dev/redirect-lab/redirectioner/routes/web.php
badd +60 ~/dev/redirect-lab/redirectioner/app/Http/Controllers/LinksController.php
badd +29 ~/dev/redirect-lab/redirectioner/app/View/Components/Links/Table.php
badd +1 ~/dev/redirect-lab/redirectioner/database/migrations
badd +1 ~/dev/redirect-lab/redirectioner/database/migrations/2019_12_14_000001_create_personal_access_tokens_table.php
badd +22 ~/dev/redirect-lab/redirectioner/database/migrations/2021_11_07_162241_create_links.php
badd +1 ~/dev/redirect-lab/redirectioner/app/View/Components/Links/Form.php
badd +16 ~/dev/redirect-lab/redirectioner/app/Models/IpAddress.php
badd +22 ~/dev/redirect-lab/redirectioner/app/Models/UserAgent.php
badd +10 ~/dev/redirect-lab/redirectioner/app/Models/LinkVisit.php
badd +18 ~/dev/redirect-lab/redirectioner/database/migrations/2021_11_07_180854_create_link_visits.php
badd +16 ~/dev/redirect-lab/redirectioner/database/migrations/2021_11_07_180606_create_ip_addresses.php
badd +11 ~/dev/redirect-lab/redirectioner/database/migrations/2021_11_07_180434_create_user_agent.php
badd +1110 ~/dev/redirect-lab/redirectioner/vendor/laravel/framework/src/Illuminate/Database/Schema/Blueprint.php
badd +1 ~/dev/redirect-lab/redirectioner/database/migrations/2021_11_07_223702_visits.php
badd +20 ~/dev/redirect-lab/redirectioner/database/migrations/2014_10_12_000000_create_users_table.php
badd +31 ~/dev/redirect-lab/redirectioner/database/seeders/DatabaseSeeder.php
badd +14 ~/dev/redirect-lab/redirectioner/.env
badd +1 ~/dev/redirect-lab/redirectioner/app/Http/Controllers/Auth/PasswordResetLinkController.php
if exists('s:wipebuf') && len(win_findbuf(s:wipebuf)) == 0
"   silent exe 'bwipe ' . s:wipebuf
endif
" unlet! s:wipebuf
set winheight=1 winwidth=20 shortmess=filnxtToOSc
let s:sx = expand("<sfile>:p:r")."x.vim"
if filereadable(s:sx)
  exe "source " . fnameescape(s:sx)
endif
let &g:so = s:so_save | let &g:siso = s:siso_save

" Support for special windows like quick-fix and plug-in windows.
" Everything down here is generated by vim-session (not supported
" by :mksession out of the box).

1wincmd w
tabnext 1
if exists('s:wipebuf')
  if empty(bufname(s:wipebuf))
if !getbufvar(s:wipebuf, '&modified')
  let s:wipebuflines = getbufline(s:wipebuf, 1, '$')
  if len(s:wipebuflines) <= 1 && empty(get(s:wipebuflines, 0, ''))
    silent execute 'bwipeout' s:wipebuf
  endif
endif
  endif
endif
doautoall SessionLoadPost
unlet SessionLoad
" vim: ft=vim ro nowrap smc=128
